//--------------------------------------------------------------------- SOL
// This file is part of abcip, a simple packet crafting tool.
// Copyright (C) 2010-2013 Charles R. Combs
//
// Abcip is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation, either version 3 of the License, or (at your
// option) any later version.
// 
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//--------------------------------------------------------------------- EOL

#include "data.h"

//-------------------------------------------------------------------------
// this is the text of scene 5 from Monty Python and the Holy Grail
//-------------------------------------------------------------------------

const string s_fullMonty = 
    "CROWD:  A witch!  A witch!  A witch!  We've got a witch!  A witch!\n"
    "VILLAGER #1:  We have found a witch, might we burn her?\n"
    "CROWD:  Burn her!  Burn!\n"
    "BEDEMIR:  How do you know she is a witch?\n"
    "VILLAGER #2:  She looks like one.\n"
    "BEDEMIR:  Bring her forward.\n"
    "WITCH:  I'm not a witch.  I'm not a witch.\n"
    "BEDEMIR:  But you are dressed as one.\n"
    "WITCH:  They dressed me up like this.\n"
    "CROWD:  No, we didn't... no.\n"
    "WITCH:  And this isn't my nose, it's a false one.\n"
    "BEDEMIR:  Well?\n"
    "VILLAGER #1:  Well, we did do the nose.\n"
    "BEDEMIR:  The nose?\n"
    "VILLAGER #1:  And the hat -- but she is a witch!\n"
    "CROWD:  Burn her!  Witch!  Witch!  Burn her!\n"
    "BEDEMIR:  Did you dress her up like this?\n"
    "CROWD:  No, no... no ... yes.  Yes, yes, a bit, a bit.\n"
    "VILLAGER #1:  She has got a wart.\n"
    "BEDEMIR:  What makes you think she is a witch?\n"
    "VILLAGER #3:  Well, she turned me into a newt.\n"
    "BEDEMIR:  A newt?\n"
    "VILLAGER #3:  I got better.\n"
    "VILLAGER #2:  Burn her anyway!\n"
    "CROWD:  Burn!  Burn her!\n"
    "BEDEMIR:  Quiet, quiet.  Quiet!"
    "  There are ways of telling whether she is a witch.\n"
    "CROWD:  Are there?  What are they?\n"
    "BEDEMIR:  Tell me, what do you do with witches?\n"
    "VILLAGER #2:  Burn!\n"
    "CROWD:  Burn, burn them up!\n"
    "BEDEMIR:  And what do you burn apart from witches?\n"
    "VILLAGER #1:  More witches!\n"
    "VILLAGER #2:  Wood!\n"
    "BEDEMIR:  So, why do witches burn?\n"
    "[pause]\n"
    "VILLAGER #3:  B--... 'cause they're made of wood...?\n"
    "BEDEMIR:  Good!\n"
    "CROWD:  Oh yeah, yeah...\n"
    "BEDEMIR:  So, how do we tell whether she is made of wood?\n"
    "VILLAGER #1:  Build a bridge out of her.\n"
    "BEDEMIR:  Aah, but can you not also build bridges out of stone?\n"
    "VILLAGER #2:  Oh, yeah.\n"
    "BEDEMIR:  Does wood sink in water?\n"
    "VILLAGER #1:  No, no.\n"
    "VILLAGER #2:  It floats!  It floats!\n"
    "VILLAGER #1:  Throw her into the pond!\n"
    "CROWD:  The pond!\n"
    "BEDEMIR:  What also floats in water?\n"
    "VILLAGER #1:  Bread!\n"
    "VILLAGER #2:  Apples!\n"
    "VILLAGER #3:  Very small rocks!\n"
    "VILLAGER #1:  Cider!\n"
    "VILLAGER #2:  Great gravy!\n"
    "VILLAGER #1:  Cherries!\n"
    "VILLAGER #2:  Mud!\n"
    "VILLAGER #3:  Churches -- churches!\n"
    "VILLAGER #2:  Lead -- lead!\n"
    "ARTHUR:  A duck.\n"
    "CROWD:  Oooh.\n"
    "BEDEMIR:  Exactly!  So, logically...,\n"
    "VILLAGER #1:  If... she.. weighs the same as a duck, she's made of wood.\n"
    "BEDEMIR:  And therefore--?\n"
    "VILLAGER #1:  A witch!\n"
    "CROWD:  A witch!\n"
    "BEDEMIR:  We shall use my larger scales!\n"
    "[yelling]\n"
    "BEDEMIR:  Right, remove the supports!\n"
    "[whop]\n"
    "[creak]\n"
    "CROWD:  A witch!  A witch!\n"
    "WITCH:  It's a fair cop.\n"
    "CROWD:  Burn her!  Burn!  [yelling]\n"
    "BEDEMIR:  Who are you who are so wise in the ways of science?\n"
    "ARTHUR:  I am Arthur, King of the Britons.\n"
    "BEDEMIR:  My liege!\n"
    "ARTHUR:  Good Sir knight, will you come with me to Camelot,\n"
    "and join us at the Round Table?\n"
    "BEDEMIR:  My liege!  I would be honored.\n"
    "ARTHUR:  What is your name?\n"
    "BEDEMIR:  Bedemir, my leige.\n"
    "ARTHUR:  Then I dub you Sir Bedemir, Knight of the Round Table.\n"
;

//-------------------------------------------------------------------------
// a fish called dubya ...
//-------------------------------------------------------------------------

static const string s_fullDubya = 
   "CROWD: A packet!  A packet!  A packet!  We've got a packet!  A packet!\n"
   "BIDEN: We have found a packet, might we route her?\n"
   "CROWD: Route her!  Route!\n"
    "GORE: How do you know she is a packet?\n"
  "MCCAIN: She looks like one.\n"
    "GORE: Forward her.\n"
   "PALIN: I'm not a packet.  I'm not a packet.\n"
    "GORE: But you are crafted as one.\n"
   "PALIN: They crafted me up like this.\n"
   "CROWD: No, we didn't... no.\n"
   "PALIN: And this isn't my header, it's a false one.\n"
    "GORE: Well?\n"
   "BIDEN: Well, we did do the header.\n"
    "GORE: The header?\n"
   "BIDEN: And the trailer -- but she is a packet!\n"
   "CROWD: Route her!  Packet!  Packet!  Route her!\n"
    "GORE: Did you craft her up like this?\n"
   "CROWD: No, no... no ... yes.  Yes, yes, a bit, a bit.\n"
   "BIDEN: She has got a option.\n"
    "GORE: What makes you think she is a packet?\n"
"GINGRICH: Well, she turned me into a frag.\n"
    "GORE: A frag?\n"
"GINGRICH: I got better.\n"
  "MCCAIN: Route her anyway!\n"
   "CROWD: Route!  Route her!\n"
    "GORE: Quiet, quiet.  Quiet!  There are ways of telling whether she is a packet.\n"
   "CROWD: Are there?  What are they?\n"
    "GORE: Tell me, what do you do with packets?\n"
  "MCCAIN: Route!\n"
   "CROWD: Route, route them up!\n"
    "GORE: And what do you route apart from packets?\n"
   "BIDEN: More packets!\n"
 "STEVENS: Tubes!\n"
    "GORE: So, why do packets route? [pause]\n"
 "STEVENS: B--... 'cause they're made of tubes...?\n"
    "GORE: Good!\n"
   "CROWD: Oh yeah, yeah...\n"
    "GORE: So, how do we tell whether she is made of tubes?\n"
 "CLINTON: Build a bridge out of her.\n"
    "GORE: Aah, but can you not also build bridges out of silicon?\n"
   "CROWD: Oh, yeah.\n"
    "GORE: Do tubes sink in water?\n"
   "BIDEN: No, no.\n"
  "MCCAIN: They float!  They float!\n"
   "BIDEN: Throw her into the pond!\n"
   "CROWD: The pond!\n"
    "GORE: What also floats in water?\n"
  "CHENEY: Oil!\n"
 "CLINTON: French fries!\n"
    "DOLE: Little blue pills!\n"
  "MCCAIN: Great mavericks!\n"
 "CLINTON: Cigars!\n"
  "CHENEY: Nukes!\n"
   "BIDEN: Botox!\n"
 "KENNEDY: Cars -- Cars!\n"
  "QUAYLE: Lead -- lead!\n"
    "BUSH: A fish.\n"
   "CROWD: Oooh.\n"
    "GORE: Exactly!  So, logically...,\n"
   "BIDEN: If... she.. weighs the same as a fish, she's made of tubes.\n"
    "GORE: And therefore--?\n"
   "BIDEN: A packet!\n"
   "CROWD: A packet!\n"
    "GORE: We shall use my larger Internet! [yelling]\n"
    "GORE: Right, remove the firewall! [click] [tap]\n"
   "CROWD: A packet!  A packet!\n"
   "PALIN: You betcha! [wink]\n"
   "CROWD: Route her!  Route!  [yelling]\n"
    "GORE: Who are you who are so wise in the ways of science?\n"
    "BUSH: I am Dubya, King of the Muricans.\n"
    "GORE: My liege!\n"
    "BUSH: Good night sir!  Will you come with me to Warshington, "
          "and join us at the Oval Office?\n"
    "GORE: My liege!  I would be honored.\n"
    "BUSH: What is your name?\n"
    "GORE: Gore, my leige.\n"
    "BUSH: Then I dubya Sir Gordo, Knight of the Oval Orifice.\n"
;

//-------------------------------------------------------------------------
// and now for something completely different ...
// text ripped from www.lipsum.com
//-------------------------------------------------------------------------

static const string s_loremIpsum = 
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam "
    "suscipit, quam at scelerisque ultricies, nisi nulla fermentum orci, a "
    "imperdiet lacus enim a felis. Cum sociis natoque penatibus et magnis "
    "dis parturient montes, nascetur ridiculus mus. Nullam dapibus risus in "
    "dolor iaculis quis lacinia est pellentesque. Maecenas ut felis est, "
    "sed interdum lorem. Cras auctor, ipsum vitae venenatis faucibus, nunc "
    "massa fermentum augue, vitae ullamcorper purus felis quis ante. Fusce "
    "feugiat enim ut nunc consectetur id ultricies tortor lobortis. "
    "Maecenas in orci metus, non interdum neque. Pellentesque vulputate "
    "ante in risus ullamcorper rutrum.  Fusce vel dapibus leo. In sed lacus "
    "nec lacus tincidunt imperdiet a vel magna. Suspendisse luctus congue "
    "imperdiet. Donec sed sagittis lorem. In hac habitasse platea dictumst. "
    "Donec sollicitudin ante et ante tincidunt ut porta elit rhoncus. "
    "Phasellus risus nunc, fringilla a tincidunt id, malesuada at sapien. "
    "Cras vitae metus justo, id auctor metus. Curabitur suscipit facilisis "
    "felis vitae pharetra. Ut eu nisi nisi. Cras condimentum euismod massa "
    "eu tristique. Donec eros nisl, semper et lacinia a, tempus id diam. "
    "Cras non tellus non sem congue mollis non ut mi. Duis diam felis, "
    "cursus non suscipit non, molestie vitae tellus. Donec facilisis dui et "
    "eros porttitor consequat.  Ut a bibendum ligula. Proin euismod porta "
    "leo a dictum. Aenean quis ipsum mauris, eu sagittis sapien. Aenean "
    "nibh metus, lobortis sed feugiat ut, fermentum vitae nibh. Cras "
    "scelerisque, ligula et aliquet vestibulum, erat massa tempus mi, ac "
    "porttitor turpis magna vel urna. Nunc in libero a augue vestibulum "
    "accumsan at ut diam. Cras dignissim facilisis risus, in dictum felis "
    "ullamcorper ac. Sed hendrerit lacus vitae mauris consequat non laoreet "
    "metus congue. Nulla facilisi. Nam ut dolor elit, et gravida nisi. "
    "Phasellus iaculis ultrices porta.  Cum sociis natoque penatibus et "
    "magnis dis parturient montes, nascetur ridiculus mus. Aenean augue "
    "turpis, malesuada ac volutpat et, aliquam a massa. Proin non massa "
    "libero, lacinia ultrices urna. Ut orci dolor, euismod a sollicitudin "
    "a, tristique quis diam. Donec faucibus dictum libero sed molestie. "
    "Integer porta, est id faucibus iaculis, eros lectus volutpat dolor, "
    "non porta urna mauris lacinia est. Integer egestas lectus in tortor "
    "auctor euismod. Fusce in velit ac mauris molestie varius eu quis "
    "ipsum. Praesent sed leo libero, eu sollicitudin sem.  Mauris ut nisl "
    "id felis elementum gravida sed sit amet libero. Etiam vitae elit "
    "justo. Cras pellentesque est eget libero sodales tristique. Ut sed "
    "lorem lacus, sit amet consectetur ante. Cras ut arcu sed nisl viverra "
    "suscipit. Praesent vitae massa nulla, sodales laoreet nulla. "
    "Pellentesque leo metus, posuere non sollicitudin ut, adipiscing quis "
    "ligula. Duis ante odio, interdum non lobortis non, consectetur in "
    "erat. Lorem ipsum sit amet dolor, consectetur adipiscing elit. "
    "Integer sapien lorem, interdum non rhoncus nec, condimentum vitae "
    "libero. Vivamus quis blandit nunc. Proin mi risus, iaculis in "
    "dignissim eu, porta et eros. Etiam quis felis a dolor consequat "
    "pretium. Praesent metus arcu, ullamcorper non blandit eu, mattis quis "
    "sapien. Praesent et dolor adipiscing lacus feugiat eleifend. Integer "
    "facilisis elementum massa, nec condimentum lectus elementum vel. "
    "Quisque nec nisi tincidunt metus sagittis vulputate a in nulla. "
    "Suspendisse ultrices nunc sit amet nisi feugiat in iaculis quam "
    "posuere. Morbi ac lacus dolor, nec dictum sem.  Praesent pharetra "
    "ipsum ac ipsum rhoncus ut dignissim urna porta. Sed nisi ante, ornare "
    "a fermentum et, pellentesque vitae elit. Fusce in ante quam, eu varius "
    "tellus. Quisque non sapien a velit eleifend blandit. Suspendisse ut "
    "tristique purus. In faucibus bibendum justo quis congue. Nunc sit amet "
    "neque sed metus rhoncus semper. Proin ornare vestibulum porttitor. "
    "Aliquam erat volutpat. Donec nec risus erat. Aliquam erat volutpat. In "
    "venenatis libero a tortor vehicula mattis. Quisque laoreet sagittis "
    "libero sed laoreet. Aliquam sed posuere metus.  Etiam aliquam "
    "porttitor elit, eget pellentesque lacus vestibulum id. Donec dictum "
    "porttitor justo quis luctus. Mauris vitae libero nisl. Nullam vel "
    "metus leo. Suspendisse elit risus, volutpat et iaculis suscipit, "
    "posuere in magna. Pellentesque volutpat magna vel arcu ultrices "
    "venenatis. Pellentesque eu posuere justo. Nam tellus nibh, iaculis sit "
    "amet sagittis vitae, vehicula a mauris. Pellentesque rhoncus risus nec "
    "dui dignissim et facilisis velit cursus. Nam tristique ultrices urna, "
    "nec condimentum eros pellentesque vitae. In in varius lorem. Morbi "
    "vitae lectus nisl. Aliquam dolor eros, dignissim sit amet ornare in, "
    "aliquam nec nunc. Proin lacinia vestibulum nibh.  Curabitur ultricies "
    "pulvinar est, et varius orci ullamcorper at. Sed sed orci dui. Cras "
    "non neque sit amet ante volutpat varius. Vivamus malesuada mollis "
    "bibendum. Quisque imperdiet, sem ac sodales cursus, dui orci mollis "
    "dui, euismod facilisis turpis ligula in erat. Aenean lobortis, sem ut "
    "tempus dignissim, lorem neque consequat eros, id aliquam magna nulla "
    "id nibh. Donec tincidunt dui at velit sagittis at ultricies dui "
    "blandit. Cras urna nunc, consectetur venenatis pellentesque vitae, "
    "mollis id velit.  Etiam id quam vel nibh vestibulum congue. Duis "
    "consequat placerat dui nec sollicitudin. Sed erat diam, pellentesque "
    "elementum mollis id, pharetra sed dolor. Morbi rhoncus interdum tortor "
    "consectetur lobortis. Donec ut arcu nec sem vestibulum egestas. Duis "
    "adipiscing ullamcorper auctor. Curabitur ut est sit amet est ultrices "
    "ullamcorper. Nulla neque nunc, accumsan ac gravida a, fermentum in "
    "libero. Sed vel euismod diam. Vestibulum laoreet tincidunt rutrum. "
    "Maecenas rhoncus luctus libero, eu pretium sem tincidunt non. Nam "
    "ipsum lectus, sagittis sit amet viverra et, aliquet eget massa. "
    "Pellentesque hendrerit nibh in lorem placerat tempus. Mauris et eros "
    "vitae lorem suscipit pretium vitae vitae lectus. In congue magna quis "
    "felis dictum in vulputate arcu egestas. Ut a commodo tortor. Sed eget "
    "quam sit amet enim tincidunt euismod in vel lacus. Nam semper metus "
    "quis leo semper dapibus. Sed nulla turpis, varius vitae posuere quis, "
    "aliquam vitae felis. Ut aliquet molestie leo, vitae pretium velit "
    "elementum quis.  Integer gravida lectus nec neque semper egestas. "
    "Integer pulvinar, metus ut hendrerit molestie, leo mauris ultricies "
    "elit, tempus vulputate dui risus nec tellus. Maecenas lobortis "
    "tristique est, a fermentum dui scelerisque et. In vitae faucibus enim. "
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac "
    "habitasse platea dictumst. Vestibulum vitae felis vel mi rhoncus "
    "pretium. Vestibulum id nibh eros, quis faucibus enim. Ut sagittis nibh "
    "vel massa fringilla at interdum mauris condimentum.  Integer a quam "
    "eros, eu scelerisque tortor. Ut euismod erat sit amet urna commodo id "
    "imperdiet justo tempus. Cras libero augue, posuere vel elementum "
    "malesuada, mollis eget mi. Pellentesque blandit porttitor nunc et "
    "viverra. Quisque eget nulla ac urna fringilla volutpat accumsan sed "
    "nibh. Vestibulum non arcu ac arcu mattis pulvinar accumsan tincidunt "
    "nisi. Duis in libero at lacus hendrerit fermentum a id sem. "
    "Pellentesque pretium neque sed dolor tincidunt vestibulum. Duis "
    "blandit purus ut nisl eleifend et sodales odio consectetur. Ut vel "
    "mauris at erat euismod vestibulum. Sed vel lacus sit amet ipsum rutrum "
    "sodales sed ut felis.  In id justo eget metus lacinia rutrum. Maecenas "
    "nisl risus, condimentum sed venenatis a, tempus id magna. Praesent sed "
    "mauris sit amet arcu imperdiet vulputate. Vivamus quis commodo libero. "
    "Fusce tincidunt congue sagittis. Nunc leo dui, semper ornare ultrices "
    "vitae, tempus at metus. Nulla venenatis dapibus tortor, non convallis "
    "tellus posuere non. Aliquam tempus mauris et nisi gravida sed pulvinar "
    "magna posuere. Mauris eu elit id ante cursus eleifend.  Ut accumsan, "
    "leo ut imperdiet condimentum, justo dolor malesuada mi, a porta augue "
    "ipsum et justo. Aenean porta arcu vel dui facilisis tincidunt. Aenean "
    "at purus nibh. Nunc vitae velit a libero tincidunt faucibus. Morbi "
    "nisi velit, venenatis quis mattis porttitor, semper id eros. "
    "Suspendisse a justo sapien. Nunc elit eros, convallis vel lobortis "
    "quis, congue sit amet nisl. Praesent vel tellus urna, vel lobortis "
    "arcu. Aliquam euismod, dui sit amet blandit rhoncus, mi ipsum luctus "
    "ligula, sed sagittis magna tortor id lectus. Proin varius commodo "
    "malesuada. Suspendisse potenti.  Quisque vel porttitor metus. "
    "Suspendisse viverra neque non orci convallis fermentum ut vel eros. "
    "Praesent rutrum volutpat metus, vitae condimentum est aliquet id. "
    "Praesent dignissim neque quis nulla fringilla ultricies. Integer dui "
    "lacus, congue et euismod a, fermentum quis mauris. Sed commodo justo "
    "non felis rhoncus rhoncus. Proin vitae libero pretium risus malesuada "
    "tempor ac fringilla lacus. Nullam feugiat ligula ut nulla vehicula "
    "sagittis laoreet a justo. Aliquam nec nibh ut augue vulputate "
    "pharetra. In scelerisque feugiat ante id hendrerit. Integer sit amet "
    "metus et augue congue egestas in ac orci.  Vivamus aliquam augue eu "
    "eros luctus in dapibus ante porta. Mauris sit amet magna dui, in "
    "accumsan ipsum. Suspendisse rhoncus viverra massa, nec gravida mi "
    "mollis a. Ut ullamcorper, metus commodo condimentum ultricies, odio "
    "purus malesuada neque, in auctor nunc ligula vulputate eros. Curabitur "
    "ullamcorper sodales ante, sit amet consectetur arcu tempor eget. "
    "Quisque eu tempor diam. Vestibulum vel sem sed mi tempus semper. "
    "Vestibulum fringilla, dolor vel mollis feugiat, eros quam euismod "
    "enim, semper scelerisque velit massa quis libero. In consequat dolor "
    "eget eros malesuada scelerisque. Duis a augue eu mauris viverra "
    "fermentum sed vel enim. Aliquam id pulvinar mi. Vivamus quis pharetra "
    "ante. Integer facilisis sodales sem, placerat laoreet eros convallis "
    "id.  Cum sociis natoque penatibus et magnis dis parturient montes, "
    "nascetur ridiculus mus. In in odio leo, vitae semper enim. Mauris "
    "auctor justo vel nisi hendrerit vulputate. Cras vel luctus turpis. "
    "Suspendisse porttitor magna et augue cursus eget convallis velit "
    "dictum. Nulla facilisi. Donec rutrum, dui et egestas fringilla, nibh "
    "augue dictum metus, id auctor nisi leo et justo. Fusce semper "
    "imperdiet nisi hendrerit mattis.  Maecenas vestibulum turpis vel sem "
    "ornare accumsan. Etiam luctus tincidunt ullamcorper. Vestibulum augue "
    "nulla, sagittis ut placerat vel, posuere vitae felis. Morbi venenatis "
    "mattis urna, non mattis ligula hendrerit id. Duis ut laoreet turpis. "
    "Vivamus augue orci, congue eget venenatis vel, posuere vel tortor. "
    "Donec aliquet, tortor ut condimentum porta, velit velit tincidunt "
    "orci, id pulvinar lorem magna egestas orci. Donec auctor, felis quis "
    "gravida cursus, quam risus interdum urna, vitae sodales diam enim at "
    "est. Proin quis diam nisi. Morbi consectetur aliquam ligula non "
    "consectetur. Morbi sit amet sem ac nunc cursus vestibulum sed vel "
    "ante. Duis egestas turpis a erat suscipit elementum. In ultricies urna "
    "quis turpis congue eget iaculis risus gravida. Duis fringilla lacinia "
    "quam quis rhoncus. Fusce semper elit at nunc varius et tempor dui "
    "facilisis.  Nunc dapibus suscipit dignissim. Vestibulum pulvinar "
    "luctus eros, ac condimentum ipsum vulputate vel. Donec sollicitudin "
    "neque non libero facilisis quis sollicitudin nulla lobortis. Vivamus "
    "tincidunt, sapien nec malesuada tincidunt, libero eros placerat magna, "
    "a lacinia ante dolor vel lacus. Nunc porttitor mauris sed mi imperdiet "
    "pellentesque. Proin nec sagittis nisl. Praesent pretium, diam vel "
    "tristique tristique, libero sapien vestibulum sem, id feugiat tellus "
    "lectus in arcu. Nulla facilisi. Fusce ac tellus feugiat tellus auctor "
    "consectetur ac id nulla. Ut orci nulla, facilisis placerat sagittis "
    "sed, volutpat quis arcu. Lorem ipsum dolor sit amet, consectetur "
    "adipiscing elit. Nulla facilisi. Fusce sollicitudin faucibus "
    "malesuada. Cras risus nulla, scelerisque non pretium id, dictum sit "
    "amet dui.  Aliquam erat volutpat. Sed eget dolor risus, et interdum "
    "lorem. Nulla in velit vitae nisl ornare iaculis. Donec porttitor arcu "
    "id urna dignissim venenatis. Mauris a ipsum lorem. Donec fringilla "
    "adipiscing diam, in venenatis tellus scelerisque sit amet. Nam vitae "
    "feugiat arcu. Sed a nisl eros.  Nunc non tortor velit. Morbi egestas "
    "pulvinar orci consequat bibendum. Aliquam ultrices libero adipiscing "
    "mi consectetur venenatis. Maecenas eu sem eget lorem bibendum faucibus "
    "ac eu velit. Sed nibh est, imperdiet consequat condimentum sit amet, "
    "convallis non sapien. Cras lobortis tincidunt ante at tempor. Maecenas "
    "at quam id magna tincidunt dignissim sed non nulla.  Suspendisse "
    "tristique tristique condimentum. Fusce dapibus pretium erat eu "
    "iaculis. Aenean quis sapien nunc. Nulla mattis metus sed justo "
    "convallis vehicula. Vivamus magna nisl, aliquam sit amet luctus a, "
    "rhoncus a libero. Vestibulum nec augue justo. Aliquam semper nulla nec "
    "enim faucibus in vehicula dolor porta. Cras vel sapien lectus. "
    "Vestibulum vel lacus in dui gravida varius nec vel mauris. Proin vitae "
    "odio purus.  Vivamus laoreet facilisis augue, suscipit rutrum risus "
    "porttitor in. Fusce quis odio vel dui ultrices aliquam. Fusce vel "
    "nulla purus, et luctus mi. Nullam non metus nisl. Fusce egestas tempus "
    "pretium. Cras non tempor nisi. Donec rutrum luctus tempor. Nam tempor "
    "est vel risus dapibus commodo. Sed augue odio, mollis et volutpat in, "
    "luctus eu nunc. Maecenas sit amet mi scelerisque tellus bibendum "
    "consectetur ut ullamcorper felis. Proin eleifend dapibus massa "
    "faucibus viverra. Aliquam congue, sem eu mattis dignissim, nisi turpis "
    "bibendum leo, id mattis risus odio a leo. Etiam ac malesuada metus. "
    "Donec elit lorem, fermentum eu lobortis et, consequat nec eros. Duis "
    "rhoncus molestie magna at porta. Ut cursus posuere fermentum. In "
    "elementum viverra pulvinar. Pellentesque tempus varius dignissim. Sed "
    "consectetur lectus ac justo aliquam non congue tellus lobortis. Duis "
    "turpis urna, consequat in mattis vitae, tempor accumsan arcu. Praesent "
    "et mi a elit sagittis placerat at tristique massa. Donec sed mi eu "
    "purus rhoncus tempus sodales vitae felis. Vivamus eu auctor diam. "
    "Donec a tortor nec ipsum tincidunt faucibus. Phasellus dapibus laoreet "
    "diam quis auctor. Nam mattis, sapien quis bibendum porta, risus est "
    "faucibus felis, ut sagittis eros turpis a arcu.  Vestibulum at pretium "
    "nisi. Vivamus mauris enim, commodo in volutpat et, laoreet nec sem. "
    "Vivamus id fermentum est. Sed sagittis posuere erat, id hendrerit "
    "turpis venenatis vel. Vestibulum turpis odio, tristique quis convallis "
    "at, ornare quis arcu. Praesent ut commodo nibh. Donec cursus nulla "
    "tincidunt nibh lacinia vehicula. Suspendisse eu nunc ante. Duis sit "
    "amet ante eu nulla auctor tincidunt luctus sed nunc.  Cras tincidunt "
    "consequat varius. Morbi lectus orci, luctus sed elementum vitae, "
    "volutpat nec dolor. Etiam hendrerit dolor quis nibh consectetur ut "
    "facilisis felis cursus. Donec vel ipsum erat, vestibulum faucibus "
    "dolor. Morbi dictum magna sed magna gravida lobortis vitae id lectus. "
    "Quisque condimentum, purus at vehicula egestas, orci felis posuere "
    "nulla, vel ultrices nunc metus id lectus. Phasellus at arcu a leo "
    "consequat lobortis et eget mi. Aliquam vel placerat nisi. Morbi at "
    "aliquam justo. Etiam sed venenatis quam. Nulla nec eros diam, eget "
    "aliquet enim. Pellentesque nisl felis, tincidunt nec ornare luctus, "
    "imperdiet sit amet diam. Fusce hendrerit, nunc a molestie sodales, "
    "enim odio ullamcorper nisi, non tincidunt orci urna quis tellus. "
    "Aenean pharetra imperdiet libero quis rhoncus.  Phasellus vehicula "
    "diam vel risus semper rhoncus. Duis velit sem, cursus vel vehicula at, "
    "dignissim nec orci. Fusce dui nisi, tempor in mattis sit amet, "
    "elementum vel libero. Praesent tempus fringilla justo vitae blandit. "
    "Morbi ac venenatis libero. Nullam volutpat dictum ornare. Quisque "
    "tincidunt gravida turpis ut malesuada. Fusce tempus auctor elementum. "
    "Duis dapibus est nulla. Suspendisse erat felis, bibendum ac iaculis "
    "quis, suscipit adipiscing arcu. Pellentesque condimentum velit tempus "
    "mauris imperdiet imperdiet. Ut enim magna, dictum quis volutpat vel, "
    "convallis eget mi.  Quisque feugiat, lacus id varius ultrices, ligula "
    "leo dapibus urna, non ullamcorper turpis leo vel elit. Ut cursus "
    "ornare lacus in ullamcorper. Sed ut orci nec lorem tincidunt cursus. "
    "Etiam placerat arcu a massa cursus quis condimentum augue consequat. "
    "Sed mollis adipiscing felis, vitae venenatis odio lacinia quis. Donec "
    "vitae malesuada augue. Vestibulum varius hendrerit mauris, eget "
    "gravida sapien imperdiet at. Morbi ac odio lacus, ac euismod nunc. "
    "Morbi ut quam arcu, id bibendum massa. Curabitur vitae dui vehicula mi "
    "mollis interdum non in libero. Proin tellus metus, imperdiet ac "
    "condimentum pharetra, malesuada ac eros. Praesent risus augue, lacinia "
    "at pharetra vel, ullamcorper ut diam.  Vestibulum et mollis dui. "
    "Aliquam erat volutpat. Nam tincidunt condimentum urna, sed vulputate "
    "felis pretium eu. Fusce aliquet facilisis ultricies. Cum sociis "
    "natoque penatibus et magnis dis parturient montes, nascetur ridiculus "
    "mus. Proin tincidunt interdum bibendum. Duis porttitor iaculis magna "
    "ac dictum. In hendrerit, elit sit amet cursus pretium, leo diam "
    "ultrices urna, vitae interdum sem mauris eu justo. Integer neque "
    "massa, consequat ut vestibulum a, tincidunt sodales risus. Duis non "
    "nulla dictum dolor commodo rutrum et eu quam. Nulla libero ligula, "
    "blandit non placerat at, viverra hendrerit lorem. Vestibulum metus "
    "erat, vestibulum at commodo non, iaculis ac neque. Donec adipiscing "
    "lacus nec nisl luctus eu lacinia erat placerat. Aenean vel pharetra "
    "erat.  Nunc dapibus ultricies nisi eu feugiat. Nullam id justo vel leo "
    "consequat mollis vitae sed magna. Morbi vel felis mi. Aenean eu libero "
    "a tellus venenatis pulvinar quis et nisi. Vestibulum venenatis purus "
    "ut quam aliquam et congue dui dictum. Sed magna nisi, tincidunt non "
    "fringilla sed, rhoncus ac dui. Nunc ut quam lobortis dolor posuere "
    "eleifend eu vitae ligula. Etiam vel diam lorem. Lorem ipsum dolor sit "
    "amet, consectetur adipiscing elit.  Etiam nec nunc felis. Ut vehicula "
    "aliquam enim in suscipit. Proin at ipsum sit amet est consectetur "
    "mattis. Mauris nec libero odio, vel vulputate mi. Sed pretium dui sit "
    "amet augue eleifend vitae tempor erat luctus. Aenean vel justo et elit "
    "aliquam vehicula. Phasellus faucibus ullamcorper vulputate. Sed ut "
    "lectus orci, sed eleifend orci. Ut hendrerit ipsum non leo rutrum et "
    "rhoncus ipsum varius. Aenean ipsum massa, dictum vitae luctus vel, "
    "adipiscing eget felis. Morbi eu risus ipsum. Ut ultricies suscipit "
    "tortor vel rhoncus. Ut eu nisi libero. Proin ligula turpis, vestibulum "
    "et lobortis sit amet, convallis nec sapien.  Suspendisse tincidunt, "
    "elit non pharetra semper, enim mi facilisis sem, ac semper urna magna "
    "at augue. In mattis, urna sed gravida fringilla, turpis lorem egestas "
    "magna, vel fringilla arcu lectus non ligula. Duis consectetur congue "
    "orci, quis porta lectus dictum et. Aliquam lobortis est a nulla "
    "aliquam sed euismod eros scelerisque. Praesent vulputate consequat leo "
    "id volutpat. Phasellus adipiscing arcu eu velit rutrum porta. Aenean "
    "eu magna dui, id lobortis odio. Vestibulum vitae ligula diam. "
    "Pellentesque habitant morbi tristique senectus et netus et malesuada "
    "fames ac turpis egestas. Maecenas dignissim, lacus quis dapibus "
    "blandit, arcu nunc venenatis nisl, eu tincidunt enim quam in arcu. "
    "Praesent venenatis fermentum arcu, in pretium arcu suscipit eu. Nam "
    "luctus diam gravida metus porta hendrerit.  Morbi sem mi, ultrices id "
    "laoreet tempus, suscipit at ante. Nam lobortis, urna a luctus auctor, "
    "eros erat faucibus velit, sed feugiat nulla mauris nec libero. "
    "Curabitur tristique hendrerit magna quis pretium. Fusce sagittis "
    "lectus at augue ultrices et ultricies elit pretium. Aenean molestie "
    "blandit faucibus. Vestibulum ante ipsum primis in faucibus orci luctus "
    "et ultrices posuere cubilia Curae; Nunc hendrerit iaculis lorem, vitae "
    "interdum nunc varius et. In hac habitasse platea dictumst. Proin ac mi "
    "metus, at interdum justo. Suspendisse vel auctor ligula. Sed interdum "
    "euismod iaculis. Mauris dictum mollis elit, eu tempus arcu lobortis "
    "auctor. Fusce faucibus elementum lacus ac euismod. Ut id sem id quam "
    "laoreet condimentum nec faucibus mauris.  Fusce eget mauris id justo "
    "placerat tempor. Quisque rhoncus suscipit lacus, sit amet fringilla "
    "magna porta quis. Nulla facilisi. Aenean vitae tellus ut orci sodales "
    "sodales. Fusce justo nulla, dictum id dignissim nec, pretium vitae "
    "tellus. Etiam aliquet, nulla id dapibus porttitor, augue nulla "
    "fringilla odio, in ultricies dolor erat consectetur justo. Morbi massa "
    "quam, convallis quis accumsan id, eleifend sed felis. Aenean dignissim "
    "turpis in metus consectetur vestibulum. Curabitur auctor nisl in nibh "
    "cursus posuere. Vivamus semper, elit nec tincidunt egestas, lacus nisi "
    "lobortis magna, eget molestie lacus velit id est. Donec lorem odio, "
    "blandit eget vestibulum in, consectetur ac tortor. Donec molestie "
    "laoreet metus non posuere. Nam laoreet posuere justo in tincidunt. "
    "Nullam est eros, scelerisque sed suscipit sollicitudin, dapibus a "
    "dolor. Donec lobortis augue ac erat suscipit non molestie erat mattis. "
    "Fusce vestibulum lacinia massa vitae auctor. Donec ac felis ante, ut "
    "blandit nulla. Maecenas consequat ultricies dolor scelerisque mattis. "
    "Suspendisse potenti. Vestibulum ante ipsum primis in faucibus orci "
    "luctus et ultrices posuere cubilia Curae; Phasellus accumsan eros nec "
    "libero posuere euismod. Integer eget tellus eu urna sollicitudin "
    "imperdiet sit amet sed purus. Pellentesque interdum lacus vitae augue "
    "interdum semper varius ante interdum. Aliquam accumsan, felis at "
    "posuere vulputate, lorem tellus consectetur ipsum, consectetur "
    "venenatis elit ante eget ante.  Aliquam erat volutpat. Aenean "
    "vestibulum condimentum ullamcorper. Maecenas faucibus diam ac ipsum "
    "suscipit mollis. Nullam faucibus elit sed lorem consequat luctus. "
    "Aliquam sodales tellus ut risus molestie a tristique dui mollis. "
    "Integer fermentum odio vel lectus aliquet et tempus felis pretium. "
    "Fusce convallis interdum dapibus.  Nam diam magna, vulputate nec "
    "luctus vel, molestie ac lorem. Nunc porta tempus diam, a gravida purus "
    "sodales a. Praesent vel massa eu eros pellentesque accumsan vitae et "
    "quam. Vestibulum quis tortor neque, id egestas diam. Aliquam sit amet "
    "mi in neque congue mattis. Maecenas ac libero sit amet dui rutrum "
    "mattis eu vitae leo. Pellentesque aliquam luctus augue sed tristique. "
    "Cras feugiat suscipit elit, sed tristique quam fermentum vel. Sed "
    "luctus neque vel mauris consectetur nec fringilla augue dictum. "
    "Integer dui nibh, euismod non tempus porta, iaculis vitae lectus. "
    "Fusce convallis egestas ligula, et vestibulum felis euismod eget. "
    "Mauris interdum tincidunt dolor, et ornare lectus placerat auctor. "
    "Maecenas ut nibh nulla. Sed nec est mauris, non rhoncus sapien. Nam "
    "blandit, felis a porttitor mollis, nibh odio placerat urna, sed "
    "pretium augue dolor ac nulla.  In hac habitasse platea dictumst. "
    "Aliquam velit leo, semper eget condimentum vitae, congue tempor "
    "sapien. Vestibulum aliquam urna laoreet sapien aliquam bibendum "
    "aliquam eros sollicitudin. Curabitur gravida malesuada molestie. Ut eu "
    "urna vel nisl sodales tincidunt. Ut tristique magna vel quam pretium "
    "euismod. Quisque non massa lacus. Sed ac massa eu dui auctor dapibus. "
    "Proin at magna ligula, varius mattis risus. Pellentesque imperdiet "
    "ultricies lacus eget sollicitudin. Integer iaculis fringilla ipsum, "
    "commodo sollicitudin neque ornare a. Phasellus ac felis nisl. Praesent "
    "tortor ipsum, rhoncus vel placerat a, auctor eget augue. Suspendisse "
    "nibh lectus, laoreet et venenatis ac, porta vel massa. Duis euismod, "
    "turpis vel adipiscing ornare, tellus turpis varius felis, in porta "
    "erat neque eget diam. Aenean vel sapien et elit gravida commodo.  Sed "
    "non mi eu mi lacinia vulputate. Pellentesque habitant morbi tristique "
    "senectus et netus et malesuada fames ac turpis egestas. In hac "
    "habitasse platea dictumst. Nullam fringilla, leo a rhoncus iaculis, "
    "tortor urna volutpat eros, eget tristique erat eros et justo. Duis "
    "vehicula imperdiet nulla. Etiam et enim ut tellus lacinia laoreet et "
    "vitae erat. Phasellus accumsan neque quam. Aenean vel sapien neque. "
    "Nam augue sapien, sollicitudin at ultrices elementum, dictum non ante. "
    "Nulla vitae dolor vitae ante bibendum ullamcorper at non nisi. Integer "
    "ut congue lorem. Morbi blandit tincidunt ligula, eget tincidunt elit "
    "facilisis vel. Aenean eleifend velit eu nibh gravida lobortis. Vivamus "
    "aliquam, odio non viverra sodales, dolor tortor mollis quam, nec "
    "convallis nisl quam quis nunc. Suspendisse eu turpis felis, id feugiat "
    "tellus. Quisque tortor enim, placerat at dictum in, adipiscing et dui. "
    "Sed vitae nulla ligula. Nunc placerat elit at lectus fringilla "
    "lacinia. Ut quis imperdiet orci. Praesent et ipsum vitae elit "
    "scelerisque ultrices. Donec neque arcu, malesuada in pellentesque sed, "
    "iaculis ac mi. Vivamus at velit sit amet mi placerat ullamcorper non "
    "sit amet lorem.  Etiam quis accumsan mi. Nullam sapien purus, gravida "
    "quis sodales ut, adipiscing in turpis. Duis nisi neque, suscipit sed "
    "tincidunt ut, semper ut neque. Sed sagittis ante et sapien imperdiet "
    "id varius metus lacinia. Nam ullamcorper bibendum erat eu lacinia. "
    "Etiam sed magna enim, id ornare magna. Integer pretium ornare sodales. "
    "Fusce leo sapien, dapibus at aliquam sit amet, lobortis sit amet ante. "
    "Maecenas viverra sollicitudin nisl eu vulputate. Quisque dictum, velit "
    "a pulvinar adipiscing, mi velit congue arcu, sit amet pretium mi "
    "turpis et augue. Ut egestas urna eu elit cursus convallis.  Donec a "
    "metus vitae diam cursus sodales. Etiam a eros id elit posuere "
    "placerat. Class aptent taciti sociosqu ad litora torquent per conubia "
    "nostra, per inceptos himenaeos. Cras eget leo nibh. Pellentesque "
    "consequat mollis commodo. Class aptent taciti sociosqu ad litora "
    "torquent per conubia nostra, per inceptos himenaeos. Duis molestie, "
    "ligula sed porttitor porta, nulla eros pulvinar libero, non blandit "
    "dui tortor vitae magna. Donec mollis lobortis risus quis pharetra. Sed "
    "sit amet magna ante, eu ornare nunc. Integer quis vestibulum augue. "
    "Duis vehicula auctor felis. Duis fermentum, ipsum at eleifend "
    "facilisis, lorem ipsum ornare arcu, eu lacinia velit lorem sed libero. "
    "Aliquam tincidunt nunc non turpis faucibus sed commodo quam "
    "condimentum. Vestibulum rutrum sollicitudin ante non sagittis. Aliquam "
    "non eros sit amet lorem pellentesque gravida in aliquet purus. "
    "Praesent vestibulum fermentum ipsum, eu blandit augue lacinia vel. "
    "Quisque ipsum mi, convallis eu fringilla at, malesuada eu tortor. "
    "Nullam volutpat sem eget turpis sagittis ornare quis et lorem. Aliquam "
    "ultricies erat enim. Class aptent taciti sociosqu ad litora torquent "
    "per conubia nostra, per inceptos himenaeos. Cras quis ipsum enim. "
    "Mauris id diam neque. Nulla a nibh at mauris commodo iaculis et ac "
    "nibh. Morbi a ipsum et libero sodales vestibulum ut non nulla. Fusce "
    "eget facilisis ligula.  Praesent aliquam mi sit amet sapien consequat "
    "viverra. Fusce ac augue magna, sed egestas est. Maecenas non tortor "
    "lacus, ut venenatis erat. Nam sed arcu ipsum. Nam id libero velit. "
    "Proin faucibus purus nec enim tempus eleifend. Nullam sit amet congue "
    "nisi. Praesent vitae tortor urna.  Aliquam tincidunt mollis orci, ut "
    "pulvinar felis auctor eu. Nunc eu purus est. Praesent consectetur, "
    "tortor at hendrerit volutpat, enim metus suscipit augue, ac facilisis "
    "lacus nisi at nunc. Fusce eleifend lorem ac augue eleifend placerat. "
    "Mauris varius hendrerit feugiat. Donec sagittis venenatis purus eget "
    "gravida. Cras bibendum vulputate tortor, eu aliquet quam iaculis quis. "
    "Proin rutrum neque quis sem vestibulum mattis. Pellentesque ut mi "
    "quam, sed vestibulum purus. Nam egestas ante id nulla consectetur "
    "sagittis. Vestibulum dapibus blandit felis a commodo. Cras nec magna "
    "risus, id scelerisque velit. In a orci risus, sed gravida nisi. Nulla "
    "gravida orci sit amet est sagittis accumsan. Proin tempor blandit "
    "accumsan. Nullam eget lectus vel nisl malesuada placerat. Nunc congue "
    "cursus massa, ut convallis eros egestas ac. Pellentesque habitant "
    "morbi tristique senectus et netus et malesuada fames ac turpis "
    "egestas.  Suspendisse lectus quam, rhoncus nec tincidunt quis, "
    "consectetur vitae nulla. Nullam vitae metus mi, et mattis tellus. "
    "Donec accumsan ante at neque mollis ultrices. Donec sollicitudin, "
    "neque eu viverra faucibus, augue nibh vehicula orci, et ultricies "
    "nulla turpis sed nunc. Nulla et massa massa, quis elementum est. Cras "
    "tincidunt lacinia convallis. Quisque auctor dictum consectetur. Nam "
    "consectetur elementum turpis, in faucibus lectus sagittis congue. "
    "Vivamus at risus tellus. Suspendisse laoreet nibh magna. Morbi sed "
    "tortor enim, nec imperdiet quam.  Sed venenatis, arcu a euismod "
    "rutrum, sem nulla egestas lectus, et ullamcorper risus dolor "
    "condimentum est. Donec eleifend congue neque, at fermentum mauris "
    "convallis quis. Duis ullamcorper fringilla diam nec tincidunt. Donec "
    "pellentesque velit non tellus lacinia porta quis at mi. Proin quis "
    "dapibus mi. Nam consectetur ullamcorper mollis. Etiam fermentum nunc "
    "placerat turpis mollis aliquet. Quisque sit amet nisl ut nibh interdum "
    "consectetur quis id mauris. Fusce ultrices arcu sit amet enim "
    "convallis tincidunt.  Fusce ultricies venenatis urna, a posuere dui "
    "hendrerit a. Mauris pulvinar auctor feugiat. Morbi in sem augue. "
    "Praesent scelerisque mollis accumsan. Nunc eu nunc nisi, sit amet "
    "ultrices leo. Curabitur tincidunt, nisl cursus pulvinar sodales, orci "
    "elit ornare ligula, non venenatis arcu nisl ut sapien. Vivamus rhoncus "
    "est at massa rhoncus volutpat. Cras pellentesque dapibus diam nec "
    "molestie. Morbi quam felis, interdum non interdum et, aliquam sed "
    "lectus. Vivamus nibh urna, venenatis non luctus eu, accumsan ac "
    "libero. Mauris posuere dapibus commodo. Class aptent taciti sociosqu "
    "ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla "
    "eget orci purus, quis ultrices neque. Praesent massa quam, posuere nec "
    "volutpat non, laoreet quis tortor.  Ut faucibus elit non est ornare "
    "luctus. Pellentesque habitant morbi tristique senectus et netus et "
    "malesuada fames ac turpis egestas. Ut iaculis dolor vel turpis aliquam "
    "porta volutpat mauris scelerisque. Mauris quis tincidunt risus. "
    "Praesent molestie, velit ut commodo sagittis, neque leo rutrum lorem, "
    "at lobortis velit mauris et nibh. Suspendisse a convallis ante. Nullam "
    "odio ipsum, blandit et congue nec, blandit non purus.  Suspendisse "
    "posuere euismod eros, aliquet tristique sapien lacinia nec. Mauris "
    "condimentum felis vitae risus egestas at aliquam sem faucibus. Nullam "
    "sit amet mauris erat. Aenean ultricies odio eu velit suscipit luctus. "
    "Phasellus mi turpis, facilisis vitae mattis ut, mattis placerat metus. "
    "Sed hendrerit orci non nisi faucibus hendrerit. Suspendisse elementum "
    "semper urna vel consectetur. Sed et adipiscing nunc. Nulla nisi diam, "
    "egestas et ultricies nec, placerat ut neque. Integer tincidunt purus "
    "nec nibh congue nec euismod libero fringilla. Suspendisse potenti. "
    "Maecenas quis justo lectus, ut mattis risus. Donec sagittis, sapien et "
    "elementum accumsan, metus magna porta justo, ac convallis neque enim "
    "ac mi. Aliquam commodo suscipit orci sed tempus. Nullam ornare lorem "
    "et erat dapibus vel feugiat felis pulvinar.  Nullam consequat felis ac "
    "mi vulputate a molestie eros adipiscing. Pellentesque interdum ornare "
    "est eget volutpat. Phasellus sodales imperdiet est eu molestie. Morbi "
    "feugiat sapien porttitor orci imperdiet ut iaculis libero tincidunt. "
    "Sed ac lobortis sem. Maecenas interdum venenatis iaculis. Donec vitae "
    "felis eros, eu scelerisque sem. Mauris consequat nisl quis leo sodales "
    "vel scelerisque nunc condimentum. Pellentesque dapibus ultricies enim "
    "nec vehicula. Cras lectus leo, fringilla eget fringilla sit amet, "
    "dapibus non turpis. Ut vel odio id eros bibendum pretium sit amet nec "
    "neque. Quisque vitae neque nibh. Ut sollicitudin augue eu enim "
    "sagittis et mattis dui vulputate.  Suspendisse potenti. Quisque quam "
    "velit, euismod ac blandit eu, posuere quis turpis. Curabitur orci "
    "ipsum, ullamcorper at feugiat id, imperdiet ac arcu. Aliquam at libero "
    "elit. Vivamus lacinia nibh vestibulum ante sagittis ut cursus metus "
    "fermentum. Nullam cursus eros vitae odio tempor fermentum. Sed "
    "sollicitudin magna eu nisl auctor vitae placerat eros fringilla. Donec "
    "tristique condimentum diam, sit amet suscipit nibh feugiat sit amet. "
    "Donec interdum eros id tellus viverra congue.  Phasellus quis sem sit "
    "amet massa facilisis lacinia at nec purus. Suspendisse at dui lacus, "
    "et volutpat orci. Phasellus quis nulla eu neque fermentum dignissim. "
    "Vivamus non eros ornare sapien varius vulputate quis pellentesque "
    "libero. Ut non hendrerit urna. Mauris eget nisi ut leo posuere lacinia "
    "vitae vitae eros. Aliquam ultricies ipsum aliquam enim ornare lacinia. "
    "Vestibulum hendrerit pharetra urna. Nulla porta euismod ante, sit amet "
    "ultrices dolor ultricies sed. Donec molestie lectus vel felis pulvinar "
    "venenatis. Class aptent taciti sociosqu ad litora torquent per conubia "
    "nostra, per inceptos himenaeos. Duis convallis, lacus id lacinia "
    "venenatis, velit nisl pretium erat, et tincidunt velit mi sed enim. "
    "Sed interdum mollis ipsum eu rutrum. Duis blandit aliquam ante sit "
    "amet lacinia.  Duis eget ante et velit pulvinar semper faucibus eget "
    "est. Nulla feugiat interdum pulvinar. Suspendisse lobortis egestas "
    "aliquam. Nulla ligula felis, vestibulum eu fermentum et, hendrerit "
    "eget lorem. Curabitur augue tortor, consectetur ac lobortis id, "
    "gravida id odio. Lorem ipsum dolor sit amet, consectetur adipiscing "
    "elit. Vestibulum hendrerit tincidunt venenatis.  Curabitur sagittis, "
    "nunc quis bibendum pharetra, eros eros elementum leo, at hendrerit "
    "velit elit quis elit. Suspendisse eu erat libero, tempor porta arcu. "
    "Praesent mattis tellus eget ipsum fringilla laoreet. Aliquam erat "
    "volutpat. Ut ut dignissim massa. Sed nec nisi arcu. Vivamus pharetra "
    "risus ac ipsum molestie elementum.  Vivamus eu accumsan urna. "
    "Vestibulum volutpat sapien at ipsum auctor ac egestas lorem pretium. "
    "Duis vitae ipsum nulla. Sed fringilla, tellus non vulputate accumsan, "
    "tellus diam pulvinar ante, mattis pulvinar est elit ut diam. Nulla "
    "aliquet tempus vehicula. Sed vel erat nisl, vel egestas tellus. "
    "Vivamus at massa enim. Phasellus ac nisi risus, at rutrum ante. "
    "Suspendisse nec libero nunc. Vestibulum id rutrum odio. Etiam "
    "condimentum sem a tortor mollis suscipit. Vestibulum a tortor vel "
    "ligula facilisis sagittis. Suspendisse potenti. Suspendisse potenti. "
    "Duis semper purus nec odio adipiscing eget porttitor mauris tempor. "
    "Donec et est at ligula gravida commodo. Vivamus mollis lacus nec leo "
    "sollicitudin a dignissim justo hendrerit. Aliquam id tellus tortor. "
    "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices "
    "posuere cubilia Curae; Quisque auctor aliquet ultrices. Duis eget "
    "lectus quis nisl mollis dictum. Cras vitae sollicitudin nibh. Nullam "
    "lorem nisl, fringilla eu cursus et, ullamcorper a tortor. Morbi at "
    "erat mauris. Pellentesque habitant morbi tristique senectus et netus "
    "et malesuada fames ac turpis egestas. Morbi lorem nulla, laoreet in "
    "imperdiet at, pharetra elementum diam. Pellentesque posuere dapibus "
    "metus id vestibulum. Sed at ante magna, vitae eleifend tortor. Morbi "
    "sapien ipsum, consectetur sit amet egestas quis, malesuada id lectus. "
    "Nunc faucibus, turpis id aliquam fringilla, velit enim tempor eros, ut "
    "mattis magna elit non ipsum. Morbi vitae sapien vitae est tincidunt "
    "faucibus. Proin ligula mauris, varius sed consectetur at, vehicula nec "
    "risus. In rhoncus cursus porttitor. Aliquam lacinia ultrices lorem et "
    "iaculis. Pellentesque mi nisl, euismod a dignissim nec, hendrerit a "
    "ante. Curabitur lacus nibh, rhoncus ut ultrices vitae, adipiscing at "
    "mi. Cras viverra metus nec dui eleifend convallis. Curabitur aliquet "
    "fringilla nulla, id dictum tellus lobortis eu. Praesent ac tortor "
    "erat, at facilisis lacus. Class aptent taciti sociosqu ad litora "
    "torquent per conubia nostra, per inceptos himenaeos. Sed convallis "
    "tortor ac risus posuere blandit.  Nunc et justo sed eros venenatis "
    "convallis. Curabitur vel erat enim. Praesent a sagittis nibh. Aliquam "
    "adipiscing arcu sit amet ipsum mollis dictum. In mattis vehicula "
    "eleifend. Pellentesque mi urna, fermentum et sollicitudin non, egestas "
    "ac lacus. Cras neque neque, aliquam quis bibendum nec, vehicula at "
    "urna.  Pellentesque sagittis augue nec arcu tempor mollis. Phasellus "
    "nec massa velit. Vestibulum non turpis magna. Ut sit amet auctor nibh. "
    "Quisque pellentesque cursus tellus, sed hendrerit tortor dapibus sed. "
    "Phasellus iaculis pellentesque mi a ultricies. Fusce eget faucibus "
    "metus. Maecenas euismod odio non magna pulvinar vel convallis tortor "
    "lacinia. Quisque non magna eget augue varius mollis.  Suspendisse "
    "potenti. Donec faucibus vestibulum dolor volutpat mattis. Morbi "
    "vestibulum vulputate libero, sit amet suscipit ligula aliquet ac. Sed "
    "a neque dui. Nulla ac erat id lectus pulvinar rhoncus. Integer vitae "
    "lectus eget orci consequat vulputate tincidunt ac est. Ut ac venenatis "
    "orci. Maecenas et ipsum odio. Donec in erat nec orci laoreet euismod. "
    "Integer odio turpis, venenatis sed tincidunt facilisis, gravida id "
    "lorem. Etiam facilisis felis nec tellus sollicitudin ut hendrerit "
    "metus ullamcorper. Quisque congue sagittis rutrum. Suspendisse "
    "potenti. Etiam at lectus a orci dignissim fringilla et ac nisi. Morbi "
    "et dolor sem. Aenean ipsum purus, tincidunt at feugiat non, sagittis "
    "non eros.  Suspendisse potenti. Nunc velit tortor, faucibus ac "
    "pulvinar at, ullamcorper eget arcu. Nunc interdum velit orci, "
    "vulputate auctor est. Maecenas libero lectus, ornare vel tincidunt sit "
    "amet, cursus placerat nunc. Phasellus venenatis porttitor porttitor. "
    "Sed sagittis lobortis orci, commodo gravida dolor condimentum eget. "
    "Fusce iaculis ornare dignissim. Proin eu egestas arcu.  Donec sed "
    "lectus non dolor hendrerit placerat id a augue. Pellentesque non lorem "
    "sed ipsum condimentum cursus. Quisque pharetra erat in lorem convallis "
    "eu mollis diam rhoncus. Etiam sapien nisi, lobortis vitae sollicitudin "
    "non, viverra sit amet enim. Praesent at nisi tincidunt enim mattis "
    "vestibulum. Mauris id felis volutpat diam scelerisque varius quis eget "
    "lacus. Integer nec erat ligula. Ut a dui erat. Proin sit amet lectus "
    "urna, a varius erat. Aenean porttitor ultrices suscipit. Suspendisse "
    "potenti. Sed lobortis pretium quam at gravida.  Quisque vulputate nibh "
    "vitae nisl rutrum cursus. Nulla facilisi. Phasellus ultrices, tellus "
    "sed posuere venenatis, tellus tortor porttitor nisl, eu mattis risus "
    "libero vel purus. Etiam a diam quam. Etiam condimentum ullamcorper leo "
    "eget consectetur. Nunc mi metus, pretium non dignissim sit amet, "
    "venenatis nec ante. Duis est metus, pulvinar eu pellentesque ut, "
    "pharetra sit amet massa.  Donec nec lectus enim, in ultrices dui. "
    "Praesent sit amet laoreet lorem. Praesent laoreet lorem sed erat "
    "rutrum mollis. Aenean at est sed lectus ullamcorper adipiscing. Cras "
    "eleifend enim at justo porta hendrerit. Nunc erat urna, luctus quis "
    "suscipit in, tempus suscipit est. Sed quis placerat felis. Sed "
    "adipiscing metus quis orci dignissim placerat. Nulla placerat "
    "tristique erat, at placerat risus tristique sit amet.  Integer id arcu "
    "turpis. Maecenas scelerisque diam ut mauris pulvinar ullamcorper. Nam "
    "id nisl erat, at auctor neque. Nulla placerat, tortor in viverra "
    "elementum, urna felis mattis ante, at viverra nulla lacus in diam. Sed "
    "dui mauris, lobortis vitae eleifend et, pulvinar a nulla. Proin "
    "porttitor, metus sit amet fringilla posuere, ligula magna scelerisque "
    "odio, vitae sagittis metus nibh id ante. Suspendisse eget leo diam, "
    "quis tristique diam. Sed dignissim, dui sit amet auctor malesuada, "
    "risus ante blandit felis, a auctor eros elit non mi. Nulla ut "
    "convallis urna. Nam id nunc magna, et pulvinar eros. Aliquam mi massa, "
    "iaculis vel posuere ac, iaculis vitae magna. Ut bibendum, ante ut "
    "posuere aliquam, lacus diam tincidunt quam, at euismod erat urna "
    "volutpat turpis.  Pellentesque sit amet convallis lectus. Cum sociis "
    "natoque penatibus et magnis dis parturient montes, nascetur ridiculus "
    "mus. Ut tellus ipsum, scelerisque ac interdum ut, euismod at purus. "
    "Etiam ligula lectus, accumsan eget cursus luctus, porta vel arcu. "
    "Vivamus sodales ipsum ut dui ullamcorper sed consequat neque "
    "convallis. Nam tincidunt sollicitudin tortor, eu posuere est rhoncus "
    "eu. Morbi fringilla sodales augue sit amet pharetra. Vivamus vitae "
    "varius magna. Mauris vitae semper ligula. Maecenas sit amet orci vel "
    "tellus scelerisque tristique.  Nam sodales est et lorem molestie "
    "suscipit. Aliquam eget mauris nulla. Fusce mi sapien, blandit faucibus "
    "scelerisque vel, consectetur ut nibh. Vivamus mi lorem, commodo a "
    "blandit et, fermentum et nunc. Integer suscipit sodales feugiat. "
    "Aenean tempor vestibulum laoreet. Nam eleifend, lectus et fermentum "
    "euismod, felis urna ultrices odio, vitae aliquam neque tortor et "
    "felis. Sed eget mauris a est varius tincidunt vel sit amet eros. "
    "Aliquam tincidunt egestas pharetra.  Nulla urna quam, euismod "
    "consequat fringilla at, bibendum eu mi. Pellentesque in ante sit amet "
    "arcu sodales convallis eget a ligula. Pellentesque ut cursus mauris. "
    "In congue dui sed neque posuere sit amet consectetur metus consequat. "
    "Nam commodo porta ligula, sed dignissim massa hendrerit ut. Vivamus "
    "elit mi, ornare sed convallis sed, vehicula quis metus. Vestibulum non "
    "est vitae ante elementum tincidunt vitae sed magna. Integer non ligula "
    "tellus, eu egestas odio. Sed faucibus erat sit amet libero convallis "
    "et suscipit ipsum tincidunt.  Sed quis mauris non tellus sodales "
    "pulvinar vitae nec lacus. Integer et nulla orci. Ut diam metus, semper "
    "vel vulputate ut, scelerisque ut nunc. In vestibulum, ligula in auctor "
    "scelerisque, ipsum orci sagittis purus, vel vulputate arcu erat a sem. "
    "Praesent convallis, arcu ac feugiat congue, magna felis placerat "
    "velit, vitae auctor ligula mauris vel odio. Maecenas volutpat mattis "
    "elit eget venenatis. Duis metus lacus, elementum vitae dapibus vel, "
    "tincidunt ut justo. Vivamus convallis placerat dictum.  Duis non purus "
    "tellus, nec ultrices purus. Ut eget dui libero, id blandit nunc. "
    "Nullam urna nisi, hendrerit sed consequat sed, pulvinar a mauris. "
    "Maecenas eu orci arcu, ut pharetra sem. Nam a ipsum est, eu feugiat "
    "quam. Vestibulum aliquet justo ut leo sagittis ultrices. Integer "
    "mollis iaculis iaculis. Nunc et enim ac urna eleifend auctor sit amet "
    "in velit. Fusce sit amet diam vel tortor tempus luctus at non metus. "
    "Duis id arcu nunc. In sit amet tortor non leo vulputate venenatis. "
    "Nunc tincidunt felis sed ipsum luctus congue. Duis nisi enim, ultrices "
    "sit amet hendrerit ut, condimentum et nibh. Donec accumsan malesuada "
    "quam, a consequat augue imperdiet nec.  Nullam tempor felis ac enim "
    "commodo malesuada. Curabitur aliquam, lorem id aliquet dignissim, "
    "felis lectus dictum purus, at laoreet libero odio in sem. Donec "
    "scelerisque est volutpat sem blandit porta. Sed porttitor tristique "
    "cursus. In eget lorem et turpis pretium laoreet. Duis scelerisque diam "
    "eget leo porttitor molestie. Duis augue massa, posuere ac malesuada "
    "quis, bibendum auctor dolor. Aliquam neque leo, lobortis sit amet "
    "sagittis at, tempus vitae lectus. Cras eu pharetra urna. Duis id magna "
    "ac quam iaculis luctus vel placerat turpis.  Fusce erat lorem, "
    "suscipit eu auctor at, luctus id neque. Donec vestibulum, nisl quis "
    "accumsan tincidunt, elit augue elementum sem, vel pretium justo erat "
    "at justo. Vestibulum quis erat nibh. Fusce purus erat, porttitor vitae "
    "congue ut, egestas a nisl. Integer non luctus urna. Curabitur feugiat "
    "arcu ut dolor imperdiet ut eleifend nisl commodo. Maecenas cursus nibh "
    "ac dolor tincidunt interdum. Integer sed dignissim erat. Duis nec "
    "lorem eget nunc lobortis dapibus a vitae diam. Nullam gravida risus et "
    "leo ultrices mattis. Vestibulum non pellentesque lectus. Duis ac nisi "
    "tortor. Class aptent taciti sociosqu ad litora torquent per conubia "
    "nostra, per inceptos himenaeos. Nunc vel elit velit. Donec luctus "
    "ornare neque vitae viverra. Aliquam erat volutpat.  Sed interdum, "
    "risus eu fermentum facilisis, tortor velit scelerisque urna, in "
    "consectetur purus risus at risus. In ipsum mauris, aliquam non "
    "ullamcorper rutrum, egestas dictum mauris. Integer lorem libero, "
    "accumsan sed malesuada at, scelerisque non neque. Mauris mattis "
    "porttitor mattis. Nullam quam magna, scelerisque sed tristique "
    "iaculis, vehicula at nulla. Donec sed quam eget dolor pellentesque "
    "volutpat ut congue neque. Nam vitae dolor at nibh feugiat condimentum. "
    "Pellentesque lorem leo, fermentum vel posuere nec, pretium vitae elit. "
    "Nullam viverra diam non dui luctus ac dignissim arcu aliquet. Class "
    "aptent taciti sociosqu ad litora torquent per conubia nostra, per "
    "inceptos himenaeos. Nam tempus quam ut velit rutrum egestas. Duis eget "
    "urna id nisi faucibus eleifend. Phasellus porttitor, eros sit amet "
    "vestibulum rutrum, libero massa adipiscing nisl, in mollis massa magna "
    "at nibh. Integer sollicitudin ipsum id felis porttitor sagittis porta "
    "et augue. Donec eleifend blandit nibh, sed ornare metus posuere at. "
    "Maecenas euismod luctus est, eget commodo nulla ullamcorper ac. "
    "Curabitur non tellus ut ipsum tempus consectetur id at odio. Sed et "
    "ipsum ante. Donec ut purus at risus posuere sodales eget quis dolor. "
    "Quisque pellentesque orci malesuada justo auctor varius. Cum sociis "
    "natoque penatibus et magnis dis parturient montes, nascetur ridiculus "
    "mus. Donec egestas lobortis turpis, ac fermentum lorem tincidunt id. "
    "Duis mattis mauris sed erat condimentum gravida.  Morbi congue magna "
    "in lectus gravida luctus. Etiam ut nibh sapien, sed fringilla tortor. "
    "Vivamus lorem velit, vestibulum eu mollis at, lacinia placerat ante. "
    "Nunc consequat dictum urna aliquet luctus. Sed sagittis, odio vel "
    "commodo aliquam, ante tellus venenatis ligula, at pulvinar nisl odio "
    "at nibh. Aenean viverra ligula vitae nibh convallis pellentesque. "
    "Integer congue suscipit cursus. Morbi rutrum, libero id vehicula "
    "cursus, libero turpis euismod tellus, vulputate porta nisi enim in "
    "orci. Pellentesque habitant morbi tristique senectus et netus et "
    "malesuada fames ac turpis egestas. Morbi blandit gravida sapien sed "
    "faucibus. Vestibulum vel purus risus. Donec a tellus felis. Nunc "
    "mollis nunc ante, a blandit diam. Curabitur malesuada sapien in est "
    "porttitor facilisis.  Nunc accumsan rhoncus rutrum. Duis euismod lacus "
    "vel quam eleifend imperdiet. Integer justo lacus, vehicula id lacinia "
    "eu, tempor varius augue. Pellentesque porta ante eu nisl rutrum non "
    "faucibus purus venenatis. Vivamus bibendum pretium ligula nec "
    "vulputate. Fusce ornare nunc neque, vel auctor eros. Praesent eget "
    "erat at diam aliquam mollis. Mauris sit amet arcu enim. Quisque nibh "
    "enim, facilisis nec placerat quis, vestibulum at augue.  Suspendisse "
    "hendrerit eros id erat molestie non pellentesque enim mattis. "
    "Pellentesque sit amet libero ac tellus tincidunt venenatis. Nulla "
    "facilisi. Suspendisse at augue ipsum, tristique consequat velit. "
    "Curabitur vitae elit vitae dui tincidunt venenatis. Quisque id felis "
    "elementum libero bibendum lobortis. Mauris pulvinar sollicitudin sem, "
    "quis porttitor eros vulputate tincidunt. Duis at leo vel quam posuere "
    "sagittis. Maecenas facilisis erat ut leo egestas ultrices. Aliquam "
    "iaculis, dui ut molestie ultricies, ipsum magna pellentesque orci, "
    "quis ullamcorper velit tortor et ligula. Duis erat felis, lacinia quis "
    "egestas sed, tempor eget ipsum. Cras luctus hendrerit turpis in "
    "laoreet. Quisque in velit leo. Duis sit amet vehicula quam. Donec a "
    "porta magna.  Nam imperdiet eros venenatis nisl fringilla sagittis. "
    "Sed elit turpis, tincidunt in adipiscing sed, mollis non quam. Nam "
    "quis lacus sed erat pulvinar volutpat sit amet non ipsum. Lorem ipsum "
    "dolor sit amet, consectetur adipiscing elit. Nam at massa mauris. Duis "
    "ultrices, metus in sagittis ullamcorper, metus turpis feugiat purus, "
    "in egestas felis erat eu ipsum. Donec auctor velit nec mi tempor et "
    "lobortis risus dictum. Cras nec velit est. Praesent laoreet convallis "
    "magna, ut hendrerit eros laoreet vitae.  Integer porttitor, metus nec "
    "suscipit condimentum, turpis justo euismod est, ac blandit purus mi id "
    "augue. Etiam tempus congue vestibulum. Proin sed lectus sodales justo "
    "pellentesque placerat. Curabitur in ornare tortor. Sed in mauris vitae "
    "lacus tempus volutpat. Morbi sit amet felis ut nunc sagittis fringilla "
    "sed facilisis libero. Quisque sit amet erat ac nisi euismod aliquet "
    "sit amet nec dolor.  Pellentesque sollicitudin dolor consectetur mi "
    "venenatis elementum. In egestas suscipit elit et interdum. Donec sed "
    "elementum mi. Ut accumsan augue at nulla volutpat volutpat sed et "
    "nunc. Proin sollicitudin ultrices arcu non volutpat. Mauris id semper "
    "ipsum. Aliquam quam neque, luctus nec feugiat et, cursus in orci. "
    "Aliquam erat ligula, facilisis blandit faucibus sit amet, ornare a "
    "ipsum. Integer dignissim consectetur volutpat. In hac habitasse platea "
    "dictumst. Vivamus enim massa, adipiscing congue congue ut, placerat "
    "eget urna. Curabitur ut leo a nisl tristique mollis. Proin feugiat "
    "venenatis felis, non fringilla diam posuere non.  In ac elit sodales "
    "libero auctor condimentum in non sapien. Quisque euismod mi et lectus "
    "suscipit vulputate. Maecenas eget lacus augue, quis posuere dui. In "
    "vel turpis sit amet nunc aliquet interdum. Pellentesque dignissim "
    "risus vel leo porta lacinia. Nulla gravida consectetur lacus "
    "pellentesque rutrum. Morbi eu pretium enim. Integer nulla eros, "
    "posuere sed bibendum in, pellentesque ut turpis. Phasellus ut ligula "
    "urna, ac vestibulum ipsum. Aliquam ante libero, tempus sed semper ac, "
    "luctus et ligula. Morbi suscipit est eu odio commodo ut tincidunt ante "
    "sollicitudin. Phasellus in dui eget erat ultricies pharetra.  Proin "
    "commodo arcu quis dui placerat ac venenatis quam lobortis. Nam ante "
    "dui, egestas vel facilisis nec, adipiscing volutpat nunc. Cum sociis "
    "natoque penatibus et magnis dis parturient montes, nascetur ridiculus "
    "mus. Nunc vitae nisi id neque tincidunt elementum. Ut tincidunt "
    "suscipit sapien eget lobortis. Donec euismod sapien vel dui fringilla "
    "eu placerat lacus ultricies. Duis eget nibh sapien. Donec et iaculis "
    "eros. Nullam at orci sed tortor venenatis porttitor in ut felis. Lorem "
    "ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum "
    "hendrerit quam, vitae consequat quam varius quis. Donec elit elit, "
    "tincidunt eget rhoncus quis, aliquet eu nibh. Curabitur risus arcu, "
    "viverra non luctus ac, ultrices id elit. Donec a enim neque. Cras "
    "fermentum velit sed quam tincidunt in venenatis ligula volutpat. "
    "Curabitur fringilla interdum tortor vel pharetra.  Morbi a felis erat, "
    "at laoreet nibh. Class aptent taciti sociosqu ad litora torquent per "
    "conubia nostra, per inceptos himenaeos. Aenean condimentum tempor "
    "pharetra. Phasellus mattis, lacus sed facilisis sollicitudin, sapien "
    "massa volutpat erat, a rhoncus sapien erat sit amet eros. Aliquam nisl "
    "urna, condimentum eget lobortis et, rhoncus non mi. Vivamus enim mi, "
    "scelerisque sed interdum eu, auctor at nulla. Proin risus lacus, "
    "semper ut mollis bibendum, viverra et massa. Vivamus posuere eros sem, "
    "a aliquam odio. Maecenas augue ante, euismod in pharetra vitae, "
    "venenatis nec erat.  Vestibulum placerat lacus vitae odio sodales "
    "interdum. Donec blandit nulla a justo luctus ut fringilla turpis "
    "vehicula. Suspendisse semper nisi erat. Morbi lacinia elit non mi "
    "ultrices ut fermentum orci posuere. Proin vel mauris velit, sit amet "
    "tempor augue. Maecenas sed sapien quis odio elementum rhoncus non a "
    "orci. Etiam pretium nisl a sapien condimentum in dictum tellus "
    "iaculis. Vestibulum non neque ac sapien ullamcorper malesuada. Vivamus "
    "fringilla porttitor placerat. Vestibulum imperdiet iaculis vehicula. "
    "Aliquam erat volutpat.  Suspendisse potenti. Aliquam viverra tempus "
    "ligula vitae mollis. Duis consequat, orci vitae imperdiet pulvinar, "
    "magna mauris hendrerit nulla, ac euismod magna lacus quis odio. "
    "Vestibulum ullamcorper justo sed est varius venenatis. Sed eu dolor "
    "tortor. Sed ullamcorper mi eu dolor gravida a volutpat orci "
    "adipiscing. Nullam eget justo massa, et accumsan mi. In fermentum "
    "velit a nisl porttitor varius.  Ut vehicula vulputate orci. Vivamus a "
    "diam odio, eget molestie mauris. In vel ipsum magna. Donec commodo, "
    "erat vel vehicula feugiat, nunc eros imperdiet ligula, quis fermentum "
    "arcu eros ut risus. Nam eget purus tellus, non commodo lectus. Sed "
    "varius ligula quis massa vestibulum aliquam. Mauris augue felis, "
    "aliquam ut sodales a, interdum eu nunc. Morbi vehicula eros sit amet "
    "quam adipiscing rhoncus. Quisque tempus pulvinar egestas. Maecenas et "
    "arcu non enim dictum tincidunt id ut massa. Donec blandit consequat "
    "mauris, vitae convallis nibh porttitor semper.  In eleifend libero "
    "vitae ligula ornare pulvinar. Integer convallis auctor odio, nec "
    "accumsan odio mattis a. Class aptent taciti sociosqu ad litora "
    "torquent per conubia nostra, per inceptos himenaeos. Maecenas eu "
    "dapibus urna. Nunc sodales sem id sem molestie a placerat lacus "
    "pharetra. Aenean consectetur massa vel quam consequat luctus. Maecenas "
    "vitae leo et nibh pharetra congue.  Vestibulum massa arcu, condimentum "
    "at hendrerit id, elementum a lorem. Donec viverra tristique enim, in "
    "suscipit libero semper quis. Ut elementum lobortis leo at blandit. Sed "
    "pharetra magna nec enim congue gravida. Nam vestibulum rhoncus mollis. "
    "Etiam et lorem et quam tincidunt imperdiet fermentum quis lacus. "
    "Quisque aliquam ultrices ligula, vitae suscipit turpis auctor vitae. "
    "Phasellus at nisi eget massa ultricies ultricies tempor at leo. Fusce "
    "viverra felis quis risus vestibulum id volutpat diam faucibus. "
    "Vestibulum suscipit commodo erat eu tempus. Aenean ipsum tellus, "
    "ultricies at hendrerit a, viverra nec ipsum. Donec lobortis enim "
    "condimentum mauris suscipit luctus.  Nunc quis nisi et massa faucibus "
    "faucibus. Maecenas lobortis, nibh non molestie fringilla, nisl ipsum "
    "ultricies diam, vel tempus nulla justo non sem. Phasellus sodales "
    "eleifend neque, eu imperdiet ipsum iaculis ac. Vivamus in ipsum eget "
    "nisl aliquam congue eu eget odio. Cras quis justo turpis, et lobortis "
    "justo. Integer et est a mi tincidunt tempus. Phasellus vitae mollis "
    "nisi. Vestibulum ut commodo ligula. Integer ac mattis elit. Donec "
    "volutpat vulputate dui, at venenatis nulla tristique vitae.  Praesent "
    "tincidunt turpis non erat cursus quis adipiscing velit eleifend. Nunc "
    "condimentum accumsan blandit. Ut quis tortor tortor. Duis aliquam "
    "dapibus neque sit amet feugiat. Mauris convallis sem sed nunc "
    "venenatis scelerisque. Aliquam ut ipsum mauris. Maecenas sit amet "
    "libero magna, eget volutpat eros.  Nulla facilisi. Sed eget interdum "
    "ipsum. Pellentesque vel lobortis risus. Integer porttitor nunc sed "
    "tellus suscipit vitae imperdiet dui lacinia. Aliquam eget facilisis "
    "odio. Nam ut dolor est. Nulla eu sem et nulla elementum cursus. Sed "
    "nunc tellus, lobortis sit amet laoreet ut, interdum sit amet enim. "
    "Nullam fermentum scelerisque orci, quis cursus elit eleifend sed. "
    "Morbi sed tortor lacus. Praesent elit velit, condimentum eget placerat "
    "non, viverra ut neque. Duis rhoncus tincidunt ante a consequat. Morbi "
    "dignissim turpis non sem congue euismod ut vitae erat. Aliquam ut enim "
    "dolor, at malesuada nibh. Integer sed dictum orci. Vestibulum ante "
    "ipsum primis in faucibus orci luctus et ultrices posuere cubilia "
    "Curae; Quisque at nibh purus, at condimentum massa. Quisque metus "
    "eros, aliquam ultrices consectetur vel, euismod quis lacus. Nullam "
    "tristique rhoncus odio quis luctus. Class aptent taciti sociosqu ad "
    "litora torquent per conubia nostra, per inceptos himenaeos. Sed "
    "aliquet faucibus gravida. Donec quis aliquet velit. Etiam egestas, "
    "eros nec congue malesuada, mi nunc tincidunt urna, quis varius dui "
    "tellus at odio. Proin convallis, nisl a convallis scelerisque, ante "
    "urna cursus massa, tincidunt varius odio neque vel erat. Mauris rutrum "
    "gravida tellus, id aliquet augue mollis porta. Suspendisse dui tortor, "
    "volutpat et sagittis quis, congue a tortor. Morbi vitae nisl vitae "
    "nunc semper lobortis at sed quam. Nullam sed diam elit. Cum sociis "
    "natoque penatibus et magnis dis parturient montes, nascetur ridiculus "
    "mus. Suspendisse ante velit, lacinia placerat lacinia ac, lacinia eu "
    "massa. Vestibulum ante ipsum primis in faucibus orci luctus et "
    "ultrices posuere cubilia Curae; Fusce malesuada odio aliquet eros "
    "ultricies sed elementum augue lacinia.  Maecenas mi odio, dapibus "
    "vitae mollis in, luctus ac mauris. In elit libero, volutpat et "
    "vehicula consectetur, feugiat vel nulla. Quisque enim elit, gravida "
    "sit amet pretium quis, dapibus eleifend lacus. Integer mauris quam, "
    "blandit vitae porttitor quis, gravida vel urna. Pellentesque habitant "
    "morbi tristique senectus et netus et malesuada fames ac turpis "
    "egestas. Maecenas ac odio massa, at interdum nisl. Integer vulputate "
    "auctor pretium. Nunc urna tortor, convallis id congue nec, dictum et "
    "diam. Donec sagittis mollis magna in semper. Aenean mattis scelerisque "
    "neque, id pharetra risus ultricies sit amet. Aliquam erat volutpat. "
    "Aenean nec pretium est. Fusce non sapien augue, eget pharetra turpis. "
    "Ut nulla justo, tempor ac dapibus id, facilisis in purus.  Praesent "
    "auctor libero vitae purus fermentum luctus. Donec magna nunc, iaculis "
    "ut egestas quis, adipiscing euismod augue. Duis placerat volutpat "
    "elit, varius rutrum augue consectetur id. Vestibulum dapibus odio "
    "dapibus felis hendrerit fringilla. Cum sociis natoque penatibus et "
    "magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit, "
    "felis sed porttitor lacinia, nunc mi elementum ligula, et sodales "
    "tellus lacus id metus. Nunc dolor enim, ultricies in convallis ac, "
    "imperdiet in neque. Ut ut lectus in mi imperdiet vulputate ac sit amet "
    "augue. Sed ut risus dolor. Donec ac libero lobortis sapien molestie "
    "fermentum sed et tellus.  Sed vel nisl nec neque fringilla "
    "pellentesque. Nunc ante nisl, tempus ac pellentesque sed, dapibus et "
    "nulla. Maecenas nisl lacus, bibendum vel posuere sed, tincidunt "
    "ullamcorper metus. Nulla feugiat cursus suscipit. Curabitur porta, "
    "urna et suscipit adipiscing, dui augue consectetur turpis, eu mollis "
    "arcu tellus vel magna. Sed pulvinar risus ornare urna interdum non "
    "luctus massa luctus. Suspendisse vel nisl ac eros ornare tempor in et "
    "orci. Sed vitae odio fermentum arcu aliquam fringilla et vitae orci. "
    "Sed tincidunt massa ut tortor malesuada tristique. Nunc a augue at "
    "elit porttitor malesuada. Ut suscipit, nisi sit amet venenatis luctus, "
    "orci erat imperdiet nisi, sit amet ultricies mi velit eu ligula. Sed "
    "volutpat tincidunt enim, ut scelerisque magna rutrum non. Lorem ipsum "
    "dolor sit amet, consectetur adipiscing elit. Ut hendrerit sem vel dui "
    "ultrices ultrices. Nam viverra scelerisque dolor at viverra. Cum "
    "sociis natoque penatibus et magnis dis parturient montes, nascetur "
    "ridiculus mus.  Suspendisse in sem diam, non mollis justo. Phasellus "
    "mattis tincidunt nunc, vel tempor nisl dapibus ut. Aliquam dolor "
    "nulla, iaculis eu consectetur ut, aliquet vitae tortor. Fusce nec "
    "neque ac mi tempor aliquet. Integer aliquet odio sit amet massa "
    "lacinia aliquam. Donec vehicula eleifend odio, et aliquam leo "
    "elementum ac. Nullam sit amet turpis enim, eu facilisis eros. "
    "Curabitur dignissim dignissim ultrices. Fusce sodales dignissim nulla, "
    "vehicula iaculis lorem dictum in. Mauris quis elit neque. Vestibulum "
    "id fermentum dolor. Proin aliquet nunc sed enim tempor lacinia.  Ut "
    "commodo risus at felis gravida eu accumsan metus porta. Nullam "
    "fringilla, metus nec tincidunt aliquet, est erat ullamcorper nunc, sed "
    "rhoncus nunc diam et eros. Maecenas ultrices, purus sed accumsan "
    "faucibus, felis turpis gravida magna, sed feugiat lectus purus sit "
    "amet lacus. In tristique, tortor sed vestibulum ullamcorper, ante urna "
    "rhoncus dolor, non sodales odio dolor ac lorem. Donec vitae libero "
    "eros. Pellentesque at sem id tortor aliquet lobortis. Nulla facilisi. "
    "In vitae erat velit. Integer vel urna sed diam aliquam volutpat "
    "venenatis in leo. Nulla non nibh a ligula molestie tempus.  Cras "
    "pharetra viverra lorem id tempor. Nulla risus lectus, interdum sed "
    "molestie dapibus, tempus in ante. Pellentesque habitant morbi "
    "tristique senectus et netus et malesuada fames ac turpis egestas. "
    "Proin vel nisi velit, quis viverra velit. Vestibulum tellus justo, "
    "pharetra in suscipit id, congue sed metus. Vivamus odio quam, auctor "
    "ac euismod tempor, pretium non justo. Mauris feugiat volutpat urna in "
    "faucibus.  Aliquam et massa mi. Aenean et magna erat. Aenean viverra "
    "risus neque, vel eleifend tellus. Phasellus ut ligula nibh. Cum sociis "
    "natoque penatibus et magnis dis parturient montes, nascetur ridiculus "
    "mus. Curabitur congue libero in nisl egestas rhoncus non in quam. "
    "Donec elementum commodo urna malesuada luctus. Proin leo sem, tempor "
    "porta ornare at, lacinia at metus. Cras aliquet erat placerat ipsum "
    "tincidunt euismod. Maecenas velit risus, cursus vitae rutrum et, "
    "vehicula at augue. Curabitur dignissim, metus quis aliquam ultricies, "
    "lectus dolor sagittis sapien, nec euismod erat augue a lectus. Sed "
    "placerat leo sed velit pellentesque quis varius libero eleifend. "
    "Suspendisse aliquet nulla sit amet eros consequat imperdiet.  Nunc "
    "quis pellentesque erat. Integer dignissim mi nec quam vestibulum id "
    "semper quam venenatis. Duis sapien ipsum, facilisis sit amet fermentum "
    "non, euismod ultricies erat. Suspendisse suscipit urna eu tellus "
    "vestibulum pulvinar. Maecenas tempor tempus interdum. In hac habitasse "
    "platea dictumst. Nam non felis at nisi pretium dictum et fermentum "
    "mauris. Nunc ultrices felis quis felis sagittis a tristique ligula "
    "convallis. Praesent quis augue feugiat nibh tristique adipiscing. Nunc "
    "malesuada tortor in lorem lacinia non iaculis dui interdum. Proin "
    "fermentum mollis arcu sed lacinia. Ut mollis tortor id tellus "
    "elementum dignissim.  Suspendisse laoreet sem id libero porttitor "
    "sodales. Duis tristique lacus lacinia nisi tempor egestas. Ut sit amet "
    "felis et nibh tempor eleifend commodo ut sapien. Pellentesque eleifend "
    "condimentum tincidunt. In tincidunt porttitor augue, ut interdum diam "
    "tincidunt vitae. Donec convallis commodo neque, non dignissim tellus "
    "sagittis vitae. Praesent et arcu sit amet ligula pretium ultricies vel "
    "laoreet orci. Maecenas viverra, eros vitae bibendum aliquet, orci "
    "mauris congue est, suscipit iaculis elit eros sit amet est. Aliquam "
    "sagittis molestie libero id rutrum.  Proin eu diam quis risus sagittis "
    "auctor eu eu massa. Ut pretium hendrerit augue egestas blandit. "
    "Praesent egestas elit eget lectus luctus a tincidunt arcu porttitor. "
    "Pellentesque accumsan massa eu felis dictum at accumsan enim "
    "scelerisque. Donec cursus accumsan pulvinar. Class aptent taciti "
    "sociosqu ad litora torquent per conubia nostra, per inceptos "
    "himenaeos. Sed tellus nibh, congue id condimentum sit amet, pharetra "
    "in lacus. Vivamus adipiscing est eu massa porttitor vestibulum.  Nulla "
    "id elementum diam. Etiam ac augue vel eros rhoncus posuere. Nulla "
    "pretium, enim lacinia placerat placerat, tellus dolor hendrerit risus, "
    "quis tempor mauris mauris sit amet est. Mauris tristique, nulla in "
    "adipiscing elementum, magna ante euismod ligula, quis dapibus purus "
    "nisi at eros. Ut condimentum malesuada sapien quis dictum. Integer "
    "ullamcorper scelerisque velit, id condimentum purus gravida in. "
    "Phasellus tincidunt, orci ut gravida ornare, urna dolor consectetur "
    "massa, in mollis eros turpis et velit. Sed semper porttitor neque quis "
    "interdum. Integer ac ipsum ut ipsum placerat tempor. Ut in neque vel "
    "eros feugiat pharetra. Aliquam fermentum auctor suscipit. Fusce "
    "sollicitudin rhoncus eros et gravida. Sed sed est ac nunc malesuada "
    "mattis. Quisque condimentum scelerisque ullamcorper.  Lorem ipsum "
    "dolor sit amet, consectetur adipiscing elit. Nunc tincidunt blandit "
    "urna, et imperdiet dolor sollicitudin eget. Curabitur nec eros id "
    "augue malesuada faucibus vel facilisis sapien. Cras malesuada semper "
    "enim, vel suscipit est adipiscing ac. Donec sem lacus, accumsan sit "
    "amet egestas nec, laoreet et urna. Duis quis odio eget neque aliquam "
    "dictum et et nisi. Vestibulum suscipit rutrum lorem non commodo. Nam "
    "sed scelerisque urna. Ut magna purus, interdum convallis congue a, "
    "hendrerit a nulla. Morbi tortor enim, venenatis vel elementum euismod, "
    "ornare id leo. Morbi vestibulum augue ut felis commodo varius. Sed "
    "varius turpis quis augue porta sed sodales orci lacinia. Proin in "
    "metus mauris. Donec dignissim interdum dui, et tincidunt turpis auctor "
    "eget. Sed iaculis molestie libero, id mollis libero auctor et. "
    "Integer sed mauris a dolor convallis feugiat. Proin tincidunt lorem at "
    "purus feugiat lobortis. Duis rhoncus, dolor ac interdum condimentum, "
    "metus ante viverra augue, viverra mi quam vel metus. Vestibulum "
    "placerat vestibulum massa, in laoreet neque pulvinar quis. Ut ornare "
    "mattis nibh nec tincidunt. Mauris a suscipit mauris. Aenean "
    "pellentesque, erat non consequat tempor, est odio venenatis dolor, "
    "quis aliquet massa nibh vitae neque.  Class aptent taciti sociosqu ad "
    "litora torquent per conubia nostra, per inceptos himenaeos. Maecenas "
    "erat lectus, dapibus vitae varius sed, posuere quis magna. Curabitur "
    "fringilla, risus ut fermentum laoreet, augue erat ultricies purus, "
    "vitae aliquet risus diam vel turpis. Suspendisse luctus euismod "
    "sodales. Ut tortor lacus, ultricies id hendrerit quis, consectetur "
    "vitae leo. Vivamus vitae pellentesque odio. Pellentesque eget nisi id "
    "leo fermentum semper ac non nulla. Nunc tincidunt, elit suscipit "
    "tincidunt suscipit, sem sem convallis risus, ac dapibus dui massa ac "
    "magna. Class aptent taciti sociosqu ad litora torquent per conubia "
    "nostra, per inceptos himenaeos. Pellentesque aliquet pulvinar feugiat. "
    "Aenean eu arcu neque, sed euismod nisl. Suspendisse mollis orci sed "
    "velit ultricies tempor porttitor mauris ultrices. Etiam id metus non "
    "leo tristique ultricies vel eget metus. In hac habitasse platea "
    "dictumst. Vestibulum ante ipsum primis in faucibus.\n";

//-------------------------------------------------------------------------
// dispense default data
//-------------------------------------------------------------------------

static DataOption s_data = DATA_LOREM_IPSUM;

void SetData (DataOption opt)
{
    s_data = opt;
}

const string& GetData ()
{
    switch ( s_data )
    {
    case DATA_FULL_MONTY: return s_fullMonty;
    case DATA_FULL_DUBYA: return s_fullDubya;
    default: break;
    }
    return s_loremIpsum;
}

